### ISSUE TITLE
Input data to word2phrase

### ISSUE THREAD

**Issue by bdlacree** [mukul13/rword2vec#2]
Great package here. I'm trying to use the word2phrase function, which asks for binary data input and a text output. The corpora I'm dealing with are in txt format. What is the best way to get these into the word2phrase function? Thanks!

**Comment by bdlacree** [comment]
The way that I've gotten around this so far is to use the prep_word2vec() function from the wordVectors package, which writes the corpus directory to a single text file, which I can then feed to word2phrase(). I just don't know if there's a way within the rword2vec package to take care of this.

**Comment by mukul13** [comment]
Hello,
  Currently there is no built-in functions to convert corpus directory to a single text file. All functions require single text file. So the way you mentioned is the only way for now. Will try to add this function in rword2vec in next few days.
Thank you.
